### Практическое задание NumPy

In [1]:
import numpy as np

In [2]:
a = [i for i in range (12,24)]
a

[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

In [4]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [7]:
b = a.reshape(3,4)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
b = a.reshape(2,6)
b

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
b = a.reshape(4,3)
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
b = a.reshape(6,2)
b

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [15]:
b = a.reshape(3,4)
c = b[1:, 2:]
c

array([[18, 19],
       [22, 23]])

In [16]:
b = a.reshape(12,1)
b

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [18]:
b = a.reshape(2, -1)
b

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [19]:
b = a.reshape(3, -1)
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
b = a.reshape(4, -1)
b

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [21]:
b = a.reshape(-1, 2)
b

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [25]:
b = a.reshape(-1, 1)
b

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [26]:
print('Да')

Да


In [27]:
a = np.random.randn(3, 4)
a

array([[ 2.27345508,  0.6929144 ,  0.0926329 ,  0.15036675],
       [-0.07775819,  1.11493749, -1.8953378 , -0.26788536],
       [ 0.70531711,  0.83433111, -1.01561848, -0.27700114]])

In [ ]:
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [33]:
b = a.reshape(1, a.size)
b

array([[ 2.27345508,  0.6929144 ,  0.0926329 ,  0.15036675, -0.07775819,
         1.11493749, -1.8953378 , -0.26788536,  0.70531711,  0.83433111,
        -1.01561848, -0.27700114]])

In [35]:
a = np.arange(20,0,-2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [36]:
b = np.arange(20,1,-2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [37]:
print('Отсутствует')

Отсутствует


In [41]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b), axis=0).size
v

10

In [42]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
A = a.reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
At = A.T
At

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [74]:
B = At.dot(A)
B

array([[ 80,  92, 104, 116],
       [ 92, 107, 122, 137],
       [104, 122, 140, 158],
       [116, 137, 158, 179]])

In [75]:
B.size

16

In [77]:
d = np.linalg.det(B)
d
print('Нет. Определитель = 0')

Нет. Определитель = 0


In [ ]:
np.random.seed(42)

In [58]:
c = np.random.randint(0, 16, 16)
c

array([ 7,  6, 10,  4,  2, 10, 11,  6, 14, 11,  6,  8,  4,  9,  4,  8])

In [59]:
C = c.reshape(4, 4)
C

array([[ 7,  6, 10,  4],
       [ 2, 10, 11,  6],
       [14, 11,  6,  8],
       [ 4,  9,  4,  8]])

In [78]:
D = B + C*10
D

array([[150, 152, 204, 156],
       [112, 207, 232, 197],
       [244, 232, 200, 238],
       [156, 227, 198, 259]])

In [79]:
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
D_inv

-65045000.000000134
4


array([[ 0.00511738, -0.0067996 ,  0.00663664, -0.00400892],
       [-0.03310016,  0.02993312,  0.02040895, -0.02158506],
       [ 0.01438266, -0.00089876, -0.00806734, -0.00056607],
       [ 0.01493305, -0.02145223, -0.01571743,  0.02562657]])

In [92]:
D_inv[np.where(D_inv < 0)] = 0
D_inv[np.where(D_inv > 0)] = 1
D_inv

array([[1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 1.]])

In [93]:
E = np.where(D_inv, B, C)
E

array([[ 80,   6, 104,   4],
       [  2, 107, 122,   6],
       [104,  11,   6,   8],
       [116,   9,   4, 179]])

In [110]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.transpose()
print(a)
mean_a = np.mean(a, axis = 0)
print()
print(mean_a)

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]

[2.  8.4]


In [112]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [113]:
x = a_centered[:,0]
y = a_centered[:,1]
a_centered_sp = np.dot(x, y)
a_centered_sp = a_centered_sp/4
a_centered_sp

2.0

### Практическое задание Pandas

A. Импортируйте библиотеку Pandas и дайте ей псевдоним pd.

In [115]:
import pandas as pd

In [117]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']}, 
                       columns = ['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [119]:
books = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3],
                     'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price': [450, 300, 350, 500, 450, 370, 290]},
                   columns = ['author_id', 'book_title', 'price'])
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [120]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [121]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [122]:
author_stat = pd.DataFrame({'min_price': authors_price.groupby('author_name')['price'].min(),
                                                'max_price': authors_price.groupby('author_name')['price'].max(),
                                                'mean_price': authors_price.groupby('author_name')['price'].mean()})
author_stat

min_price  max_price  mean_price
author_name                                  
Островский         290        370  330.000000
Тургенев           300        450  366.666667
Чехов              450        500  475.000000